### ISSUE TITLE
Dependencies should be added automatically

### ISSUE THREAD

**Issue by nicol-ograve** [teobler/swr-request-generator#3]
The files imported as dependencies (useGetRequest, useGetMutation) should be created automatically by the library during the generation process

**Comment by teobler** [comment]
Thanks for your feedback @nicol-ograve , I will update them with my free time

**Comment by teobler** [comment]
Since not everyone need to default request hook and default client, added two options: `needRequestHook` and `needClient`.
Config these two options as `true`, then it will generate them automatically, details can refer to [changelog](https://github.com/teobler/swr-request-generator/blob/main/changelog.md) / [readme](https://github.com/teobler/swr-request-generator/blob/main/README.md) / [example](https://github.com/teobler/swr-request-generator/tree/main/example)

**Comment by nicol-ograve** [comment]
Thank you so much @teobler
