### ISSUE TITLE
[Feature request] Add support for the "default" response type

### ISSUE THREAD

**Issue by SudoHenk** [teobler/swr-request-generator#7]
I'm currently generating an OpenAPI specification with the help of Apache CXF OpenAPI. This returns by default the following response object:

```
"responses" : {
          "default" : {
            "description" : "default response",
            "content" : {
              "application/json; charset=UTF-8" : {
                "schema" : {
                  "$ref" : "#/components/schemas/MyCustomDTO"
                }
              }
            }
          }
        }
```

I noticed that the generator only looks for the "200" response type, would it be possible to also add the "default" response type as a return type?

And another thing I noticed, is that the content.*/* wildcard is not working, I'm currently using a "application/json; charset=UTF-8" content type due to some special characters, but the wildcard is not catching this content type AFAIK.

**Comment by teobler** [comment]
1. As [describing responses](https://swagger.io/docs/specification/describing-responses/) mentioned, default response should used to describe default error like an error boundary, but I can also add it for you, its just a small adding.
2. media type '*/*' is not a wildcard in the code, it is just a specific type '*/*', since this is for my own project 😆 , I can also add your specific media type
